{
 "title": "mysql homologacao",
 "description": "Streamline and optimize important metrics with Node Exporter v0.16+. Contains: CPU memory Disk IO network temperature and other monitoring indicators. https://github.com/starsliao/Prometheus translated by Google :-) ",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d"
   },
   {
    "name": "env",
    "label": "surroundings",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "name",
    "label": "CPU name",
    "query": {
     "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
    }
   },
   {
    "name": "node",
    "label": "IP",
    "query": {
     "query": "label_values(node_exporter_build_info{name=~'$name'},instance)"
    }
   },
   {
    "name": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Tempo de execução do sistema",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"0.0.0.0:9100\"}"
    }
   ]
  },
  {
   "title": "Número de auditoria da CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Taxa de uso da CPU（5m）",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"0.0.0.0:9100\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU iowait（Tempo de Espera）",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"0.0.0.0:9100\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Uso de memória",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"0.0.0.0:9100\"} / (node_memory_MemTotal_bytes{instance=\"0.0.0.0:9100\"})))* 100"
    }
   ]
  },
  {
   "title": "Arquivos abertos na máquina",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=\"0.0.0.0:9100\"}"
    }
   ]
  },
  {
   "title": "Uso de partição Root",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"0.0.0.0:9100\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=\"0.0.0.0:9100\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Memória total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"0.0.0.0:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Carga média do sistema",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"0.0.0.0:9100\"}",
     "legendFormat": "Processos corrente"
    },
    {
     "expr": "node_load5{instance=\"0.0.0.0:9100\"}",
     "legendFormat": "Processo de memória"
    },
    {
     "expr": "node_load15{instance=\"0.0.0.0:9100\"}",
     "legendFormat": "Processo Zumbi"
    }
   ]
  },
  {
   "title": "Tamanho do disco",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 5 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes {instance=\"0.0.0.0:9100\",fstype=~\"ext4|xfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Espaço livre para cada partição",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {instance=\"0.0.0.0:9100\",fstype=~\"ext4|xfs\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=\"0.0.0.0:9100\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=\"0.0.0.0:9100\",fstype=~\"ext4|xfs\"})"
    },
    {}
   ]
  },
  {
   "title": "Uso da CPU, disco I/O operações por segundo (%))",
   "type": "graph",
   "description": "Node_disk_io_time_seconds_total:\nThe number of milliseconds the disk spends on input/output operations. This value is the accumulated value. (Milliseconds Spent Doing I/Os)\n\nIrate(node_disk_io_time_seconds_total[1m]):\nCalculate the rate per second: (last value - last previous value) / timestamp difference, that is: the percentage of time that the disk spends on I/O operations in 1 second.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"0.0.0.0:9100\",mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "Total de uso de disco do sistema"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"0.0.0.0:9100\",mode=\"user\"}[1m])) by (instance)",
     "legendFormat": "Processos em uso do sistema"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"0.0.0.0:9100\",mode=\"iowait\"}[1m])) by (instance)",
     "legendFormat": "Total de uso da CPU"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"0.0.0.0:9100\"}[1m])",
     "legendFormat": "i/O de Disco e CPU"
    }
   ]
  },
  {
   "title": "Informação da memória",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"0.0.0.0:9100\"}",
     "legendFormat": "Total memória"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"0.0.0.0:9100\"} - node_memory_MemAvailable_bytes{instance=\"10.128.0.26:9100\"}",
     "legendFormat": "Uso de memória"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"10.128.0.26:9100\"}",
     "legendFormat": "Bytes disponíveis de memória"
    }
   ]
  },
  {
   "title": "Taxa de leitura e gravação em disco (IOPS)",
   "type": "graph",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每Reads completed: Reads per second for each disk partition\n\nWrites completed: Write completions per second for each disk partition\n\nIO now The number of input/output requests being processed per second per disk partition个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "iops", "label": "read（-）/write（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"0.0.0.0:9100\"}[1m])",
     "legendFormat": "Leitura em disco"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"0.0.0.0:9100\"}[1m])",
     "legendFormat": "Escrita em disco"
    }
   ]
  },
  {
   "title": "Capacidade de leitura e gravação em disco",
   "type": "graph",
   "description": "Read bytes The number of bits read per second per disk partition\nWritten bytes The number of bits written per second per disk partition",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "Bps", "label": "read（-）/write（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"0.0.0.0:9100\"}[1m])",
     "legendFormat": "Capacidade de leitura do disco"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"0.0.0.0:9100\"}[1m])",
     "legendFormat": "Capacidade de gravação do disco"
    }
   ]
  },
  {
   "title": "Tempo de leitura e gravação do disco IO",
   "type": "graph",
   "description": "Read time ms The number of seconds per disk partition read operation\n\nWrite time ms The number of seconds per disk partition write operation\n\nIO time ms Number of seconds spent per disk partition input/output operation\n\nIO time weighted Weighted seconds spent per disk partition input/output operation",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s", "label": "read（-）/ write（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=\"0.0.0.0:9100\"}[1m])",
     "legendFormat": "Tempo de leitura de disco"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=\"0.0.0.0:9100\"}[1m])",
     "legendFormat": "Tempo de gravação de disco"
    }
   ]
  },
  {
   "title": "Disco",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=\"0.0.0.0:9100\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=\"0.0.0.0:9100\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Espaço livre de disco"
    }
   ]
  },
  {
   "title": "Tráfego de rede",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bps", "label": "upload（-）/download（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"0.0.0.0:9100\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "Download de rede"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"0.0.0.0:9100\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "Upload de rede"
    }
   ]
  },
  {
   "title": "Situação de conexão TCP",
   "type": "graph",
   "description": "CurrEstab - number of TCP connections with current state of ESTABLISHED or CLOSE-WAIT\n\nActiveOpens - TCP average connections that have been converted from the CLOSED state to the SYN-SENT state (within 1 minute)\n\nPassiveOpens - TCP average connections that have been converted from the LISTEN state to the SYN-RCVD state (within 1 minute)\n\nTCP_alloc - the number of TCP sockets that have been allocated (established, applied to sk_buff)\n\nTCP_inuse - the number of TCP sockets being used (listening)\n\nTCP_tw - number of TCP connections waiting to be closed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=\"0.0.0.0:9100\"}",
     "legendFormat": "Conexão estabilizadas"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=\"0.0.0.0:9100\"}",
     "legendFormat": "Número de conexão aguardando fechamento"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=\"0.0.0.0:9100\"}[1m])",
     "legendFormat": "Conexões convertida de fechado para sincronizado"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=\"0.0.0.0:9100\"}[1m])",
     "legendFormat": "Conexões convertida de listado para sincronizado"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=\"0.0.0.0:9100\"}",
     "legendFormat": "Número de soquetes alocados"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=\"0.0.0.0:9100\"}",
     "legendFormat": "Número  de soquetes em uso"
    }
   ]
  }
 ]
}